export const avatars = [
  "https://i.ibb.co/0Gq9FDm/avatar-1.png",
  "https://i.ibb.co/pjSz5Qs/avatar-2.png",
  "https://i.ibb.co/zGGsk3b/avatar-3.png",
  "https://i.ibb.co/Yk38JDy/avatar-4.png",
  "https://i.ibb.co/cyHKWxF/avatar-5.png",
  "https://i.ibb.co/myh51j9/avatar-6.png",
  //   "https://i.ibb.co/pzX66CC/avatar-7.png",
  //   "https://i.ibb.co/kg971cX/avatar-8.png",
  //   "https://i.ibb.co/L9HwzPk/avatar-9.png",
  //   "https://i.ibb.co/tzQ4Npv/avatar-10.png",
  //   "https://i.ibb.co/W04VgMn/avatar-11.png",
  "https://i.ibb.co/74ZRwj7/avatar-12.png",
  "https://i.ibb.co/r3ryY3G/avatar-13.png",
  "https://i.ibb.co/fq8xLyS/avatar-14.png",
  "https://i.ibb.co/k5tBmk5/avatar-15.png",
  "https://i.ibb.co/vc4cxPK/avatar-16.png",
  "https://i.ibb.co/n3tCTrK/avatar-17.png",
];
